# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba9fc6c515a901228ce952ab7edf20fc148e543dd9d2101c57dc85e802d024c3d3674fb6d2d271ef4d6dd4d037655e7244b1aa68d5944ccb8b32d00379b7275a

test:
  secret_key_base: bfc18a6f3342e151170449094138639a7f8c75d7abf13eda1916c9e7f5979154a27d61d32cf7f1e617e281cc78220a2e4ed831d67da1286f540f3ba0e577dfaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
